<?php 
$listado_clases= "
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" active\"' ondragstart=\"evdragstart(event,this)\"  >active</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" affix\"' ondragstart=\"evdragstart(event,this)\"  >affix</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" alert-danger\"' ondragstart=\"evdragstart(event,this)\"  >alert-danger</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" alert-dismissable\"' ondragstart=\"evdragstart(event,this)\"  >alert-dismissable</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" alert-info\"' ondragstart=\"evdragstart(event,this)\"  >alert-info</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" alert-link\"' ondragstart=\"evdragstart(event,this)\"  >alert-link</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" alert-success\"' ondragstart=\"evdragstart(event,this)\"  >alert-success</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" alert-warning\"' ondragstart=\"evdragstart(event,this)\"  >alert-warning</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" alert\"' ondragstart=\"evdragstart(event,this)\"  >alert</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" arrow\"' ondragstart=\"evdragstart(event,this)\"  >arrow</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" badge\"' ondragstart=\"evdragstart(event,this)\"  >badge</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" bottom\"' ondragstart=\"evdragstart(event,this)\"  >bottom</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" breadcrumb\"' ondragstart=\"evdragstart(event,this)\"  >breadcrumb</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-block\"' ondragstart=\"evdragstart(event,this)\"  >btn-block</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-danger\"' ondragstart=\"evdragstart(event,this)\"  >btn-danger</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-default\"' ondragstart=\"evdragstart(event,this)\"  >btn-default</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-group-justified\"' ondragstart=\"evdragstart(event,this)\"  >btn-group-justified</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-group-vertical\"' ondragstart=\"evdragstart(event,this)\"  >btn-group-vertical</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-group\"' ondragstart=\"evdragstart(event,this)\"  >btn-group</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-info\"' ondragstart=\"evdragstart(event,this)\"  >btn-info</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-lg\"' ondragstart=\"evdragstart(event,this)\"  >btn-lg</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-link\"' ondragstart=\"evdragstart(event,this)\"  >btn-link</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-primary\"' ondragstart=\"evdragstart(event,this)\"  >btn-primary</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-success\"' ondragstart=\"evdragstart(event,this)\"  >btn-success</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-warning\"' ondragstart=\"evdragstart(event,this)\"  >btn-warning</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn-xs\"' ondragstart=\"evdragstart(event,this)\"  >btn-xs</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" btn\"' ondragstart=\"evdragstart(event,this)\"  >btn</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" caption\"' ondragstart=\"evdragstart(event,this)\"  >caption</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" caret\"' ondragstart=\"evdragstart(event,this)\"  >caret</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" carousel-caption\"' ondragstart=\"evdragstart(event,this)\"  >carousel-caption</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" carousel-control\"' ondragstart=\"evdragstart(event,this)\"  >carousel-control</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" carousel-indicators\"' ondragstart=\"evdragstart(event,this)\"  >carousel-indicators</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" carousel-inner\"' ondragstart=\"evdragstart(event,this)\"  >carousel-inner</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" carousel\"' ondragstart=\"evdragstart(event,this)\"  >carousel</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" checkbox-inline\"' ondragstart=\"evdragstart(event,this)\"  >checkbox-inline</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" checkbox\"' ondragstart=\"evdragstart(event,this)\"  >checkbox</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" close\"' ondragstart=\"evdragstart(event,this)\"  >close</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-1\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-10\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-11\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-12\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-12</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-2\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-3\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-4\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-5\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-6\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-7\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-8\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-9\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-0\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-0</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-1\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-10\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-11\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-2\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-3\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-4\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-5\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-6\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-7\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-8\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-offset-9\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-offset-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-0\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-0</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-1\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-10\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-11\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-2\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-3\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-4\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-5\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-6\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-7\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-8\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-pull-9\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-pull-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-0\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-0</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-1\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-10\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-11\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-2\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-3\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-4\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-5\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-6\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-7\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-8\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-lg-push-9\"' ondragstart=\"evdragstart(event,this)\"  >col-lg-push-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-1\"' ondragstart=\"evdragstart(event,this)\"  >col-md-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-10\"' ondragstart=\"evdragstart(event,this)\"  >col-md-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-11\"' ondragstart=\"evdragstart(event,this)\"  >col-md-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-12\"' ondragstart=\"evdragstart(event,this)\"  >col-md-12</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-2\"' ondragstart=\"evdragstart(event,this)\"  >col-md-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-3\"' ondragstart=\"evdragstart(event,this)\"  >col-md-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-4\"' ondragstart=\"evdragstart(event,this)\"  >col-md-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-5\"' ondragstart=\"evdragstart(event,this)\"  >col-md-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-6\"' ondragstart=\"evdragstart(event,this)\"  >col-md-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-7\"' ondragstart=\"evdragstart(event,this)\"  >col-md-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-8\"' ondragstart=\"evdragstart(event,this)\"  >col-md-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-9\"' ondragstart=\"evdragstart(event,this)\"  >col-md-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-0\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-0</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-1\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-10\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-11\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-2\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-3\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-4\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-5\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-6\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-7\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-8\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-offset-9\"' ondragstart=\"evdragstart(event,this)\"  >col-md-offset-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-0\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-0</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-1\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-10\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-11\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-2\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-3\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-4\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-5\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-6\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-7\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-8\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-pull-9\"' ondragstart=\"evdragstart(event,this)\"  >col-md-pull-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-0\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-0</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-1\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-10\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-11\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-2\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-3\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-4\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-5\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-6\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-7\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-8\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-md-push-9\"' ondragstart=\"evdragstart(event,this)\"  >col-md-push-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-1\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-10\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-11\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-12\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-12</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-2\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-3\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-4\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-5\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-6\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-7\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-8\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-9\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-1\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-10\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-11\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-2\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-3\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-4\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-5\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-6\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-7\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-8\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-offset-9\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-offset-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-1\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-10\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-11\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-2\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-3\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-4\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-5\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-6\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-7\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-8\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-pull-9\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-pull-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-1\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-10\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-11\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-2\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-3\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-4\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-5\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-6\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-7\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-8\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-sm-push-9\"' ondragstart=\"evdragstart(event,this)\"  >col-sm-push-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-1\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-10\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-10</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-11\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-11</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-12\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-12</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-2\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-3\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-4\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-5\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-6\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-7\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-7</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-8\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-8</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col-xs-9\"' ondragstart=\"evdragstart(event,this)\"  >col-xs-9</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" col\"' ondragstart=\"evdragstart(event,this)\"  >col</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" collapse\"' ondragstart=\"evdragstart(event,this)\"  >collapse</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" collapsing\"' ondragstart=\"evdragstart(event,this)\"  >collapsing</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" container\"' ondragstart=\"evdragstart(event,this)\"  >container</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" control-label\"' ondragstart=\"evdragstart(event,this)\"  >control-label</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" divider\"' ondragstart=\"evdragstart(event,this)\"  >divider</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" dropdown-backdrop\"' ondragstart=\"evdragstart(event,this)\"  >dropdown-backdrop</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" dropdown-header\"' ondragstart=\"evdragstart(event,this)\"  >dropdown-header</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" dropdown-menu\"' ondragstart=\"evdragstart(event,this)\"  >dropdown-menu</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" dropdown-toggle\"' ondragstart=\"evdragstart(event,this)\"  >dropdown-toggle</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" dropdown\"' ondragstart=\"evdragstart(event,this)\"  >dropdown</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" fade\"' ondragstart=\"evdragstart(event,this)\"  >fade</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" form-control-static\"' ondragstart=\"evdragstart(event,this)\"  >form-control-static</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" form-control\"' ondragstart=\"evdragstart(event,this)\"  >form-control</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" form-group\"' ondragstart=\"evdragstart(event,this)\"  >form-group</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" glyphicon-chevron-right\"' ondragstart=\"evdragstart(event,this)\"  >glyphicon-chevron-right</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" glyphicon\"' ondragstart=\"evdragstart(event,this)\"  >glyphicon</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" h1\"' ondragstart=\"evdragstart(event,this)\"  >h1</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" h2\"' ondragstart=\"evdragstart(event,this)\"  >h2</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" h3\"' ondragstart=\"evdragstart(event,this)\"  >h3</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" h4\"' ondragstart=\"evdragstart(event,this)\"  >h4</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" h5\"' ondragstart=\"evdragstart(event,this)\"  >h5</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" h6\"' ondragstart=\"evdragstart(event,this)\"  >h6</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" help-block\"' ondragstart=\"evdragstart(event,this)\"  >help-block</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" hidden-lg\"' ondragstart=\"evdragstart(event,this)\"  >hidden-lg</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" hidden-md\"' ondragstart=\"evdragstart(event,this)\"  >hidden-md</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" hidden-print\"' ondragstart=\"evdragstart(event,this)\"  >hidden-print</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" hidden-sm\"' ondragstart=\"evdragstart(event,this)\"  >hidden-sm</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" hidden-xs\"' ondragstart=\"evdragstart(event,this)\"  >hidden-xs</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" hidden\"' ondragstart=\"evdragstart(event,this)\"  >hidden</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" hide\"' ondragstart=\"evdragstart(event,this)\"  >hide</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" icon-bar\"' ondragstart=\"evdragstart(event,this)\"  >icon-bar</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" icon-next\"' ondragstart=\"evdragstart(event,this)\"  >icon-next</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" img-circle\"' ondragstart=\"evdragstart(event,this)\"  >img-circle</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" img-responsive\"' ondragstart=\"evdragstart(event,this)\"  >img-responsive</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" img-rounded\"' ondragstart=\"evdragstart(event,this)\"  >img-rounded</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" img-thumbnail\"' ondragstart=\"evdragstart(event,this)\"  >img-thumbnail</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" in\"' ondragstart=\"evdragstart(event,this)\"  >in</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" initialism\"' ondragstart=\"evdragstart(event,this)\"  >initialism</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" input-group-addon\"' ondragstart=\"evdragstart(event,this)\"  >input-group-addon</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" input-group-btn\"' ondragstart=\"evdragstart(event,this)\"  >input-group-btn</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" input-group\"' ondragstart=\"evdragstart(event,this)\"  >input-group</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" input-lg\"' ondragstart=\"evdragstart(event,this)\"  >input-lg</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" input-sm\"' ondragstart=\"evdragstart(event,this)\"  >input-sm</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" invisible\"' ondragstart=\"evdragstart(event,this)\"  >invisible</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" item\"' ondragstart=\"evdragstart(event,this)\"  >item</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" jumbotron\"' ondragstart=\"evdragstart(event,this)\"  >jumbotron</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" label-danger\"' ondragstart=\"evdragstart(event,this)\"  >label-danger</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" label-default\"' ondragstart=\"evdragstart(event,this)\"  >label-default</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" label-info\"' ondragstart=\"evdragstart(event,this)\"  >label-info</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" label-primary\"' ondragstart=\"evdragstart(event,this)\"  >label-primary</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" label-success\"' ondragstart=\"evdragstart(event,this)\"  >label-success</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" label-warning\"' ondragstart=\"evdragstart(event,this)\"  >label-warning</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" label\"' ondragstart=\"evdragstart(event,this)\"  >label</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" lead\"' ondragstart=\"evdragstart(event,this)\"  >lead</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" left\"' ondragstart=\"evdragstart(event,this)\"  >left</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" list-group-item-heading\"' ondragstart=\"evdragstart(event,this)\"  >list-group-item-heading</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" list-group-item-text\"' ondragstart=\"evdragstart(event,this)\"  >list-group-item-text</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" list-group-item\"' ondragstart=\"evdragstart(event,this)\"  >list-group-item</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" list-group\"' ondragstart=\"evdragstart(event,this)\"  >list-group</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" list-inline\"' ondragstart=\"evdragstart(event,this)\"  >list-inline</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" list-unstyled\"' ondragstart=\"evdragstart(event,this)\"  >list-unstyled</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" media-body\"' ondragstart=\"evdragstart(event,this)\"  >media-body</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" media-heading\"' ondragstart=\"evdragstart(event,this)\"  >media-heading</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" media-list\"' ondragstart=\"evdragstart(event,this)\"  >media-list</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" media-object\"' ondragstart=\"evdragstart(event,this)\"  >media-object</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" media\"' ondragstart=\"evdragstart(event,this)\"  >media</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal-backdrop\"' ondragstart=\"evdragstart(event,this)\"  >modal-backdrop</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal-body\"' ondragstart=\"evdragstart(event,this)\"  >modal-body</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal-content\"' ondragstart=\"evdragstart(event,this)\"  >modal-content</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal-dialog\"' ondragstart=\"evdragstart(event,this)\"  >modal-dialog</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal-footer\"' ondragstart=\"evdragstart(event,this)\"  >modal-footer</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal-header\"' ondragstart=\"evdragstart(event,this)\"  >modal-header</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal-open\"' ondragstart=\"evdragstart(event,this)\"  >modal-open</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal-title\"' ondragstart=\"evdragstart(event,this)\"  >modal-title</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" modal\"' ondragstart=\"evdragstart(event,this)\"  >modal</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" nav-divider\"' ondragstart=\"evdragstart(event,this)\"  >nav-divider</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" nav-justified\"' ondragstart=\"evdragstart(event,this)\"  >nav-justified</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" nav-tabs-justified\"' ondragstart=\"evdragstart(event,this)\"  >nav-tabs-justified</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" nav-tabs\"' ondragstart=\"evdragstart(event,this)\"  >nav-tabs</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" nav\"' ondragstart=\"evdragstart(event,this)\"  >nav</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-brand\"' ondragstart=\"evdragstart(event,this)\"  >navbar-brand</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-btn\"' ondragstart=\"evdragstart(event,this)\"  >navbar-btn</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-collapse\"' ondragstart=\"evdragstart(event,this)\"  >navbar-collapse</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-default\"' ondragstart=\"evdragstart(event,this)\"  >navbar-default</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-fixed-bottom\"' ondragstart=\"evdragstart(event,this)\"  >navbar-fixed-bottom</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-fixed-top\"' ondragstart=\"evdragstart(event,this)\"  >navbar-fixed-top</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-form\"' ondragstart=\"evdragstart(event,this)\"  >navbar-form</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-header\"' ondragstart=\"evdragstart(event,this)\"  >navbar-header</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-inverse\"' ondragstart=\"evdragstart(event,this)\"  >navbar-inverse</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-left\"' ondragstart=\"evdragstart(event,this)\"  >navbar-left</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-link\"' ondragstart=\"evdragstart(event,this)\"  >navbar-link</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-nav\"' ondragstart=\"evdragstart(event,this)\"  >navbar-nav</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-right\"' ondragstart=\"evdragstart(event,this)\"  >navbar-right</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-static-top\"' ondragstart=\"evdragstart(event,this)\"  >navbar-static-top</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-text\"' ondragstart=\"evdragstart(event,this)\"  >navbar-text</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar-toggle\"' ondragstart=\"evdragstart(event,this)\"  >navbar-toggle</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" navbar\"' ondragstart=\"evdragstart(event,this)\"  >navbar</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" next\"' ondragstart=\"evdragstart(event,this)\"  >next</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" page-header\"' ondragstart=\"evdragstart(event,this)\"  >page-header</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" pager\"' ondragstart=\"evdragstart(event,this)\"  >pager</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" pagination\"' ondragstart=\"evdragstart(event,this)\"  >pagination</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-body\"' ondragstart=\"evdragstart(event,this)\"  >panel-body</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-danger\"' ondragstart=\"evdragstart(event,this)\"  >panel-danger</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-default\"' ondragstart=\"evdragstart(event,this)\"  >panel-default</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-footer\"' ondragstart=\"evdragstart(event,this)\"  >panel-footer</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-heading\"' ondragstart=\"evdragstart(event,this)\"  >panel-heading</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-info\"' ondragstart=\"evdragstart(event,this)\"  >panel-info</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-primary\"' ondragstart=\"evdragstart(event,this)\"  >panel-primary</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-success\"' ondragstart=\"evdragstart(event,this)\"  >panel-success</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-title\"' ondragstart=\"evdragstart(event,this)\"  >panel-title</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel-warning\"' ondragstart=\"evdragstart(event,this)\"  >panel-warning</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" panel\"' ondragstart=\"evdragstart(event,this)\"  >panel</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" pill-pane\"' ondragstart=\"evdragstart(event,this)\"  >pill-pane</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" popover-content\"' ondragstart=\"evdragstart(event,this)\"  >popover-content</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" popover-title\"' ondragstart=\"evdragstart(event,this)\"  >popover-title</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" popover\"' ondragstart=\"evdragstart(event,this)\"  >popover</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" pre-scrollable\"' ondragstart=\"evdragstart(event,this)\"  >pre-scrollable</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" prettyprint\"' ondragstart=\"evdragstart(event,this)\"  >prettyprint</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" prev\"' ondragstart=\"evdragstart(event,this)\"  >prev</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" progress-bar-danger\"' ondragstart=\"evdragstart(event,this)\"  >progress-bar-danger</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" progress-bar-info\"' ondragstart=\"evdragstart(event,this)\"  >progress-bar-info</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" progress-bar-success\"' ondragstart=\"evdragstart(event,this)\"  >progress-bar-success</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" progress-bar-warning\"' ondragstart=\"evdragstart(event,this)\"  >progress-bar-warning</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" progress-bar\"' ondragstart=\"evdragstart(event,this)\"  >progress-bar</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" progress\"' ondragstart=\"evdragstart(event,this)\"  >progress</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" pull-left\"' ondragstart=\"evdragstart(event,this)\"  >pull-left</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" pull-right\"' ondragstart=\"evdragstart(event,this)\"  >pull-right</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" right\"' ondragstart=\"evdragstart(event,this)\"  >right</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" row\"' ondragstart=\"evdragstart(event,this)\"  >row</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" show\"' ondragstart=\"evdragstart(event,this)\"  >show</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" sr-only\"' ondragstart=\"evdragstart(event,this)\"  >sr-only</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" table-bordered\"' ondragstart=\"evdragstart(event,this)\"  >table-bordered</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" table-responsive\"' ondragstart=\"evdragstart(event,this)\"  >table-responsive</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" table\"' ondragstart=\"evdragstart(event,this)\"  >table</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-center\"' ondragstart=\"evdragstart(event,this)\"  >text-center</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-danger\"' ondragstart=\"evdragstart(event,this)\"  >text-danger</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-hide\"' ondragstart=\"evdragstart(event,this)\"  >text-hide</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-info\"' ondragstart=\"evdragstart(event,this)\"  >text-info</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-left\"' ondragstart=\"evdragstart(event,this)\"  >text-left</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-muted\"' ondragstart=\"evdragstart(event,this)\"  >text-muted</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-primary\"' ondragstart=\"evdragstart(event,this)\"  >text-primary</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-right\"' ondragstart=\"evdragstart(event,this)\"  >text-right</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-success\"' ondragstart=\"evdragstart(event,this)\"  >text-success</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" text-warning\"' ondragstart=\"evdragstart(event,this)\"  >text-warning</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" thumbnail\"' ondragstart=\"evdragstart(event,this)\"  >thumbnail</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" tooltip-arrow\"' ondragstart=\"evdragstart(event,this)\"  >tooltip-arrow</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" tooltip-inner\"' ondragstart=\"evdragstart(event,this)\"  >tooltip-inner</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" tooltip\"' ondragstart=\"evdragstart(event,this)\"  >tooltip</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" top\"' ondragstart=\"evdragstart(event,this)\"  >top</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" visible-lg\"' ondragstart=\"evdragstart(event,this)\"  >visible-lg</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" visible-md\"' ondragstart=\"evdragstart(event,this)\"  >visible-md</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" visible-print\"' ondragstart=\"evdragstart(event,this)\"  >visible-print</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" visible-sm\"' ondragstart=\"evdragstart(event,this)\"  >visible-sm</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" visible-xs\"' ondragstart=\"evdragstart(event,this)\"  >visible-xs</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" well-lg\"' ondragstart=\"evdragstart(event,this)\"  >well-lg</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" well-sm\"' ondragstart=\"evdragstart(event,this)\"  >well-sm</div>
<div class='btn btn-default btn-block' style='cursor:move;'  draggable='true' id=' class= \" well\"' ondragstart=\"evdragstart(event,this)\"  >well</div>
";
?>